version: '3'

services:
  ptz.frw.webapi:
    image: ptz.frw.webapi
    build:
      context: .
      dockerfile: PTZ.Frw.WebAPI/Dockerfile
    depends_on:
     - sql.data
  sql.data:
    image: microsoft/mssql-server-linux
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5434:1433"